config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  match "blogs/new", :via => :post, :as => 'new_blog_post'

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  match "contacts/new", :via => :post, :as => 'new_contact_post'

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    # @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
    @notifications = Notification.where(user_id: current_user.id).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <h2>お知らせ</h2>
  <table class="table" id="notification-table">
    <% @notifications.each do |notification| %>
      <tr>
        <td>
          <% if notification.read? %>
            <span>既読</span>
          <% elsif %>
            <span><strong>未読</strong></span>
          <% end %>
        </td>
        <td>
          <%= notification.comment.user.try(:name) %>さんが
          あなたのブログ（<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>）にコメントしました。
        </td>
        <td><%= posted_time(notification.created_at) %></td>
      </tr>
    <% end %>
  </table>
</div>