config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end

  match "blogs/new", :via => :post, :as => 'new_blog_post'

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  match "contacts/new", :via => :post, :as => 'new_contact_post'

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # お問い合わせ一覧を @contacts に格納し、new.html.erb のデバッグ出力に渡す
  before_action :set_all

  def new
    if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact = Contact.new
    end
  end

  def create
    @contact = Contact.new(contacts_params)
    if @contact.save
      # 入力フォームへ遷移して"お問い合わせありがとうございました！"とメッセージを表示します。
      #redirect_to new_contact_path, notice: "お問い合わせありがとうございました！"
      # トップページへ遷移して"お問い合わせが完了しました！"とメッセージを表示します。
      redirect_to root_path, notice: "お問い合わせが完了しました！"
      NoticeMailer.sendmail_contact(@contact).deliver
    else
      # 入力フォームを再描画します。
      render action: 'new'
    end
  end

  def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?
  end

  private
    def contacts_params
      params.require(:contact).permit(:name, :email, :content)
    end

    # お問い合わせ一覧を @contacts に格納する
    def set_all
      @contacts = Contact.all
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@contact) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>
      
      <p>名前: <%= @contact.name %></p>
      <p>メールアドレス: <%= @contact.email %></p>
      <p>内容: <%= @contact.content %></p>
      <%= f.submit "登録する", class: 'btn btn-primary btn-block' %>
    <% end %>
    
    <%#= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
    <%# new アクションへのパスを、デフォルトの get から post に変更 %>
    <%= form_for(@contact, url: new_contact_post_path) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

<%
=begin
%>
<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>
  
  <p>Name: <%= @contact.name %></p>
  <p>Email: <%= @contact.email %></p>
  <p>Content: <%= @contact.content %></p>
  <%= f.submit "登録する" %>
<% end %>

<%#= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
<%# new アクションへのパスを、デフォルトの get から post に変更 %>
<%= form_for(@contact, url: new_contact_post_path) do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back' %>
<% end %>
<%
=end
%>

app/views/contacts/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>お問い合わせを入力する</h2>
    <%= form_for(@contact, url: confirm_contacts_path) do |f| %>
      <%= f.error_messages! %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>
      <br>
      <%= f.label :メールアドレス %>
      <%= f.text_field :email, class: 'form-control' %>
      <br>
      <%= f.label :内容 %>
      <%= f.text_area :content, :rows=>"5", class: 'form-control' %>
      <br>
      <%= f.submit '送信', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

<%
=begin
%>
<p><%= notice %></p>

<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= @contact.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>
<%
=end
%>

<%
=begin
%>
<h4>##### DEBUG: show contacts table #####</h4>

<table border="1" align="center">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>email</th>
    <th>content</th>
    <th>created_at</th>
    <th>updated_at</th>
  </tr>
  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.id %></td>
      <td><%= contact.name %></td>
      <td><%= contact.email %></td>
      <td><%= contact.content %></td>
      <td><%= contact.created_at %></td>
      <td><%= contact.updated_at %></td>
    </tr>
  <% end %>
</table>
<%
=end
%>